apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 12.0.0
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [auth]
    disable_login_form = false
    [auth.generic_oauth]
    allow_sign_up = true
    api_url = http://172.16.30.203/auth/realms/isiGPU/protocol/openid-connect/userinfo
    auth_url = http://172.16.30.203/auth/realms/isiGPU/protocol/openid-connect/auth
    auto_login = true
    client_id = kubeflow-oidc-authservice
    client_secret = urQd4BnZAmKuPkqoOCB4vlIneeWIdYCj
    email_attribute_path = email
    enabled = true
    icon = signin
    login_attribute_path = username
    login_prompt = login
    name = Keycloak
    name_attribute_path = full_name
    role_attribute_path = contains(realm_access.roles[*], 'admin') && 'Admin' || 'Viewer'
    scopes = openid email profile
    signout_redirect_url = http://172.16.30.203/auth/realms/isiGPU/protocol/openid-connect/logout
    tls_skip_verify_insecure = true
    token_url = http://172.16.30.203/auth/realms/isiGPU/protocol/openid-connect/token
    use_refresh_token = true
    [date_formats]
    default_timezone = Asia/Tehran
    [security]
    allow_embedding = true
    [server]
    domain = 172.16.30.205
    root_url = http://172.16.30.205/grafana/
    serve_from_sub_path = true
type: Opaque
